/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\styles\themes\matviet\matvietTheme.ts
 * Command: astryx theme build src\styles\themes\matviet\matvietTheme.ts
 * Generated: 2026-07-07T04:04:06.341Z
 */

import type { DefinedTheme } from "@astryxdesign/core/theme";
import type { IconRegistry } from "@astryxdesign/core/Icon";
export declare const neutralIconRegistry: IconRegistry;
export declare const matvietTheme: DefinedTheme;
