/**
 * Database types — compatibility layer over the Drizzle D1 schema (ADR 0009).
 *
 * Before the pivot this file was generated by `supabase gen types`. It now derives
 * the same `Database` / `Tables` / `TablesInsert` / `TablesUpdate` shapes from
 * `src/db/schema.ts`, so the whole app keeps its import surface. New code may import
 * from `@/db/schema` directly; UI code should keep using these aliases.
 */
import type * as s from "@/db/schema";

export type Json = s.Json;

type Model<T extends { $inferSelect: unknown; $inferInsert: unknown }> = {
  Row: T["$inferSelect"];
  Insert: T["$inferInsert"];
  Update: Partial<T["$inferInsert"]>;
};

/**
 * Legacy `profiles` shape, now backed by the better-auth `users` table.
 * `src/lib/auth.ts` synthesizes these rows (full_name ← name, avatar_url ← image).
 */
export interface ProfileRow {
  id: string;
  full_name: string | null;
  role: Database["public"]["Enums"]["user_role"];
  department_id: string | null;
  phone: string | null;
  avatar_url: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

type TableMap = {
  ai_screenings: Model<typeof s.ai_screenings>;
  approvals: Model<typeof s.approvals>;
  assessment_invite_tokens: Model<typeof s.assessment_invite_tokens>;
  assessment_submissions: Model<typeof s.assessment_submissions>;
  assessments: Model<typeof s.assessments>;
  audit_log: Model<typeof s.audit_log>;
  candidates: Model<typeof s.candidates>;
  cv_files: Model<typeof s.cv_files>;
  departments: Model<typeof s.departments>;
  email_messages: Model<typeof s.email_messages>;
  email_templates: Model<typeof s.email_templates>;
  employees: Model<typeof s.employees>;
  inbox_attachments: Model<typeof s.inbox_attachments>;
  interview_attendees: Model<typeof s.interview_attendees>;
  interview_evaluations: Model<typeof s.interview_evaluations>;
  interviews: Model<typeof s.interviews>;
  job_assignments: Model<typeof s.job_assignments>;
  jobs: Model<typeof s.jobs>;
  people: Model<typeof s.people>;
  positions: Model<typeof s.positions>;
  referrals: Model<typeof s.referrals>;
  scoring_queue: Model<typeof s.scoring_queue>;
  stage_history: Model<typeof s.stage_history>;
  weight_templates: Model<typeof s.weight_templates>;
  profiles: { Row: ProfileRow; Insert: ProfileRow; Update: Partial<ProfileRow> };
};

export type Database = {
  public: {
    Tables: TableMap;
    Enums: {
      ai_screening_status: (typeof s.AI_SCREENING_STATUSES)[number];
      approval_status: (typeof s.APPROVAL_STATUSES)[number];
      approval_step_kind: (typeof s.APPROVAL_STEP_KINDS)[number];
      candidate_source: (typeof s.CANDIDATE_SOURCES)[number];
      email_direction: (typeof s.EMAIL_DIRECTIONS)[number];
      email_status: (typeof s.EMAIL_STATUSES)[number];
      employee_status: (typeof s.EMPLOYEE_STATUSES)[number];
      flow_type: (typeof s.FLOW_TYPES)[number];
      interview_status: (typeof s.INTERVIEW_STATUSES)[number];
      interview_type: (typeof s.INTERVIEW_TYPES)[number];
      interviewer_role: (typeof s.INTERVIEWER_ROLES)[number];
      job_status: (typeof s.JOB_STATUSES)[number];
      pipeline_stage: (typeof s.PIPELINE_STAGES)[number];
      recommendation: (typeof s.RECOMMENDATIONS)[number];
      role_family: (typeof s.ROLE_FAMILIES)[number];
      scoring_job_status: (typeof s.SCORING_JOB_STATUSES)[number];
      user_role: (typeof s.USER_ROLES)[number];
    };
  };
};

export type Tables<T extends keyof TableMap> = TableMap[T]["Row"];
export type TablesInsert<T extends keyof TableMap> = TableMap[T]["Insert"];
export type TablesUpdate<T extends keyof TableMap> = TableMap[T]["Update"];
