/**
 * Custom Worker entrypoint wrapping the OpenNext-generated handler so we can
 * add a `scheduled()` cron handler (wrangler.jsonc `triggers.crons`).
 *
 * The cron drains both queues by invoking the app's own API routes in-process
 * (no public round-trip, no duplicated business logic in the entrypoint).
 *
 * `.open-next/worker.js` is generated by `opennextjs-cloudflare build` — run
 * that before `wrangler deploy` / `wrangler dev` (see package.json scripts).
 */
// @ts-ignore — generated at build time
import handler from "./.open-next/worker.js";

const CRON_ROUTES = ["/api/scoring/drain", "/api/emails/drain", "/api/notifications/cron"];

/** One-time-per-isolate boot check (renovation R5): without CRON_SECRET every
 * cron drain 503s and CVs spin forever with no user-visible signal. Log loudly
 * (and to Sentry when configured) — never throw, the app must still serve. */
let bootChecked = false;
function assertBootEnv(env: CloudflareEnv): void {
  if (bootChecked) return;
  bootChecked = true;
  if (!env.CRON_SECRET) {
    console.error(
      "[boot] CRON_SECRET is missing — cron drains will 503 and scoring/email queues will never flush. Set it via `wrangler secret put CRON_SECRET`.",
    );
  }
  if (!env.BETTER_AUTH_SECRET) {
    console.error("[boot] BETTER_AUTH_SECRET is missing — sessions cannot be signed.");
  }
}

/** Invoke one of the app's own API routes in-process (no public round-trip). */
async function invokeRoute(
  path: string,
  env: CloudflareEnv,
  ctx: ExecutionContext,
): Promise<Response> {
  const base = env.NEXT_PUBLIC_APP_URL || "https://hr.matviet.com.vn";
  const request = new Request(new URL(path, base), {
    headers: { authorization: `Bearer ${env.CRON_SECRET ?? ""}` },
  });
  return (await handler.fetch(request, env, ctx)) as Response;
}

/**
 * An idle drain pass (200 + all-zero counters) is the every-minute steady
 * state — logging it flooded the observability dashboard (3 lines/min).
 * Only log when the run actually did something or went wrong.
 */
function isIdleResult(status: number, body: string): boolean {
  if (status !== 200) return false;
  try {
    const data = JSON.parse(body) as Record<string, unknown>;
    return Object.values(data).every((v) => v === 0 || v === "idle" || v === false || v == null);
  } catch {
    return false;
  }
}

export default {
  fetch(request: Request, env: CloudflareEnv, ctx: ExecutionContext) {
    assertBootEnv(env);
    return handler.fetch(request, env, ctx);
  },

  async scheduled(controller: ScheduledController, env: CloudflareEnv, ctx: ExecutionContext) {
    assertBootEnv(env);
    for (const path of CRON_ROUTES) {
      try {
        const res = await invokeRoute(path, env, ctx);
        const body = await res.text();
        if (!isIdleResult(res.status, body)) {
          console.log(`[cron ${controller.cron}] ${path} -> ${res.status} ${body}`);
        }
      } catch (err) {
        console.error(`[cron ${controller.cron}] ${path} failed:`, err);
      }
    }

    // Daily sweeps — HRM compliance clock (H1) + hiring reconcile (agentic
    // audit P1). From 01:00 UTC (≈ 08:00 VN) onward every tick asks
    // /api/agent/daily, which runs AT MOST once per VN day behind a settings
    // marker — so a missed 01:00 tick (deploy, cold start) catches up on the
    // next minute instead of skipping the day. A skipped call is the idle case.
    if (new Date().getUTCHours() >= 1) {
      try {
        const res = await invokeRoute("/api/agent/daily", env, ctx);
        const body = await res.text();
        if (!(res.status === 200 && body.includes('"skipped":true'))) {
          console.log(`[cron ${controller.cron}] /api/agent/daily -> ${res.status} ${body}`);
        }
      } catch (err) {
        console.error(`[cron ${controller.cron}] /api/agent/daily failed:`, err);
      }
    }
  },

  /**
   * SCORING_QUEUE consumer — the fast path for CV scoring. Each batch runs in
   * its own invocation (no 30s waitUntil cap). The drain claims due rows from
   * the D1 scoring_queue table (the real ledger), so message payloads only
   * size the batch; retries/dedup live in D1.
   */
  async queue(batch: MessageBatch, env: CloudflareEnv, ctx: ExecutionContext) {
    const limit = Math.max(1, Math.min(batch.messages.length, 5));
    try {
      const res = await invokeRoute(`/api/scoring/drain?limit=${limit}`, env, ctx);
      console.log(
        `[queue scoring] batch=${batch.messages.length} -> ${res.status} ${await res.text()}`,
      );
    } catch (err) {
      console.error("[queue scoring] drain failed:", err);
    }
    // Always ack — the D1 queue table owns retry state, not Cloudflare Queues.
    batch.ackAll();
  },
} satisfies ExportedHandler<CloudflareEnv>;

// Re-export Durable Object classes the OpenNext runtime may reference.
// @ts-ignore — generated at build time
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";

// App-authored Durable Objects (ADR 0020) — bound in wrangler.jsonc.
export { HiringAgent } from "./src/agents/hiring-agent";
